modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="hp_output"
version="1.1.0"
displayName="HP Output"
authors="yomo40"
description='''
Broadcasts player health via UDP to localhost.
Supports damage, heal, and death events.

Configure UDP port in mod settings.
'''

[[dependencies.hp_output]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.hp_output]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="CLIENT"
